# docker build . -f Dockerfile.deb -t deb_builder

FROM ubuntu

RUN apt update -y && apt install -y cmake gcc g++ make
COPY . /tmp
RUN cd /tmp && \
    mkdir build && \
    cd build && \
    cmake .. -DLIBMBUS_PACKAGE_DEB=ON && \
    cpack .. && \
    ls -al && \
    dpkg -i *.deb

